repos:
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit -r . -c pyproject.toml
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        always_run: true
        pass_filenames: false