name: autocreate-bump-dependencies-issue

on:
    workflow_dispatch:
    schedule:
        -   cron: "17 2 1 * *"

jobs:
    create_issue:
        name: Create bump dependencies issue
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            -   name: Get current date
                id: date
                run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
            -   name: Create bump dependencies issue
                run: |
                    gh issue create \
                      --title "$TITLE" \
                      --assignee "$ASSIGNEES" \
                      --label "$LABELS" \
                      --body "$BODY" \
                      --project "$PROJECT"
                env:
                    GH_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
                    GH_REPO: ${{ github.repository }}
                    TITLE: Bump dependencies ${{ steps.date.outputs.date }}
                    ASSIGNEES: gaborschulz
                    LABELS: maintenance
                    BODY: |
                        Update package dependencies
                    PROJECT: Development
