name: build-docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/*'
      - mkdocs.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --verbose --only docs
      - run: mkdocs gh-deploy --force --clean --verbose