name: pytest

on:
    pull_request:
        types:
            - opened
            - reopened
        branches:
            - main
    push:
        # Pattern matched against refs/tags
        tags:
            - v*           # Push events to every tag not containing /

env:
    TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ '3.11' ]

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python ${{matrix.python-version}}
                uses: actions/setup-python@v3
                with:
                    python-version: ${{matrix.python-version}}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install pdm
                    pdm install
            -   name: Run tests
                run: pytest